development:
  adapter: postgresql
  encoding: unicode
  database: rails-framework_development
  pool: 5
  username: nblanchet
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: rails-framework_production
#   pool: 5
#   username: rails-framework
#   password:
